//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessories_Product
    {
        public int id_Product { get; set; }
        public string id_Accessories { get; set; }
        public string Cord { get; set; }
        public Nullable<double> Angle { get; set; }
        public int Count { get; set; }
    
        public virtual Accessories Accessories { get; set; }
        public virtual Product Product { get; set; }
    }
}
