//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentFactory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarmentFactoryEntities : DbContext
    {
        public GarmentFactoryEntities()
            : base("name=GarmentFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessories> Accessories { get; set; }
        public virtual DbSet<Accessories_Product> Accessories_Product { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Compound> Compound { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_Order> Product_Order { get; set; }
        public virtual DbSet<Textile> Textile { get; set; }
        public virtual DbSet<Textile_Stock> Textile_Stock { get; set; }
        public virtual DbSet<TypeAccessories> TypeAccessories { get; set; }
        public virtual DbSet<TypePicture> TypePicture { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
