//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Textile_Stock
    {
        public int id { get; set; }
        public int id_Textile { get; set; }
        public int Lenght { get; set; }
        public int Width { get; set; }
    
        public virtual Textile Textile { get; set; }
    }
}
